In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [7]:
x_train

age  gender  fever   cough       city
2    42    Male  101.0    Mild      Delhi
89   46    Male  103.0  Strong  Bangalore
45   72    Male   99.0    Mild  Bangalore
25   23    Male    NaN    Mild     Mumbai
22   71  Female   98.0  Strong    Kolkata
..  ...     ...    ...     ...        ...
77    8  Female  101.0    Mild    Kolkata
11   65  Female   98.0    Mild     Mumbai
47   18  Female  104.0    Mild  Bangalore
17   40  Female   98.0  Strong      Delhi
58   23    Male   98.0  Strong     Mumbai

[80 rows x 5 columns]

# Aam Jindagi

In [8]:
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])
x_test_fever=si.fit_transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [9]:
x_train_fever


array([[101. ],
       [103. ],
       [ 99. ],
       [100.9],
       [ 98. ],
       [104. ],
       [101. ],
       [101. ],
       [101. ],
       [ 98. ],
       [100. ],
       [100. ],
       [100.9],
       [101. ],
       [ 98. ],
       [101. ],
       [100. ],
       [ 98. ],
       [ 98. ],
       [100. ],
       [100.9],
       [100. ],
       [102. ],
       [100.9],
       [103. ],
       [ 98. ],
       [104. ],
       [101. ],
       [100.9],
       [104. ],
       [102. ],
       [102. ],
       [104. ],
       [100.9],
       [104. ],
       [103. ],
       [101. ],
       [102. ],
       [103. ],
       [100. ],
       [104. ],
       [ 99. ],
       [ 99. ],
       [103. ],
       [100. ],
       [104. ],
       [102. ],
       [100. ],
       [ 99. ],
       [101. ],
       [100.9],
       [ 98. ],
       [104. ],
       [102. ],
       [ 98. ],
       [101. ],
       [100. ],
       [104. ],
       [100.9],
       [ 98. ],
       [100. ],
       [ 98. ],
       [

# Ordinal Encoding -> cough

In [10]:
oe= OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])

x_test_cough=oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

# OneHot Encoding -> city, gender

In [11]:
ohe= OneHotEncoder(drop='first', sparse_output=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])

#also on test data
x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [12]:
import sklearn
print(sklearn.__version__)


1.5.1


In [13]:
# extracting age
x_train_age= x_train.drop(columns=['gender','fever','cough','city']).values

x_test_age= x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape


(80, 1)

In [14]:
x_train_transformed= np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

x_test_transformed= np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

x_train_transformed

array([[ 42. , 101. ,   1. ,   1. ,   0. ,   0. ,   0. ],
       [ 46. , 103. ,   1. ,   0. ,   0. ,   0. ,   1. ],
       [ 72. ,  99. ,   1. ,   0. ,   0. ,   0. ,   0. ],
       [ 23. , 100.9,   1. ,   0. ,   0. ,   1. ,   0. ],
       [ 71. ,  98. ,   0. ,   0. ,   1. ,   0. ,   1. ],
       [ 12. , 104. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [ 81. , 101. ,   0. ,   0. ,   0. ,   1. ,   0. ],
       [ 34. , 101. ,   0. ,   1. ,   0. ,   0. ,   1. ],
       [ 47. , 101. ,   1. ,   0. ,   0. ,   0. ,   1. ],
       [ 83. ,  98. ,   1. ,   1. ,   0. ,   0. ,   0. ],
       [ 19. , 100. ,   0. ,   0. ,   0. ,   0. ,   1. ],
       [ 47. , 100. ,   0. ,   0. ,   0. ,   0. ,   1. ],
       [ 42. , 100.9,   0. ,   0. ,   0. ,   0. ,   1. ],
       [ 20. , 101. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [ 24. ,  98. ,   1. ,   0. ,   1. ,   0. ,   0. ],
       [ 19. , 101. ,   1. ,   1. ,   0. ,   0. ,   0. ],
       [ 27. , 100. ,   1. ,   1. ,   0. ,   0. ,   0. ],
       [ 34. ,

# Mentos Jindagi

In [15]:
import sklearn
print(sklearn.__version__)


1.5.1


In [16]:
from sklearn.compose import ColumnTransformer


In [20]:
transformer= ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'),['gender','city'])
], remainder='passthrough' )
     

In [21]:
transformer.fit_transform(x_train).shape

(80, 7)

In [22]:
transformer.fit_transform(x_train)

array([[101. ,   0. ,   1. ,   1. ,   0. ,   0. ,  42. ],
       [103. ,   1. ,   1. ,   0. ,   0. ,   0. ,  46. ],
       [ 99. ,   0. ,   1. ,   0. ,   0. ,   0. ,  72. ],
       [100.9,   0. ,   1. ,   0. ,   0. ,   1. ,  23. ],
       [ 98. ,   1. ,   0. ,   0. ,   1. ,   0. ,  71. ],
       [104. ,   0. ,   0. ,   0. ,   0. ,   0. ,  12. ],
       [101. ,   0. ,   0. ,   0. ,   0. ,   1. ,  81. ],
       [101. ,   1. ,   0. ,   1. ,   0. ,   0. ,  34. ],
       [101. ,   1. ,   1. ,   0. ,   0. ,   0. ,  47. ],
       [ 98. ,   0. ,   1. ,   1. ,   0. ,   0. ,  83. ],
       [100. ,   1. ,   0. ,   0. ,   0. ,   0. ,  19. ],
       [100. ,   1. ,   0. ,   0. ,   0. ,   0. ,  47. ],
       [100.9,   1. ,   0. ,   0. ,   0. ,   0. ,  42. ],
       [101. ,   0. ,   0. ,   0. ,   0. ,   0. ,  20. ],
       [ 98. ,   0. ,   1. ,   0. ,   1. ,   0. ,  24. ],
       [101. ,   0. ,   1. ,   1. ,   0. ,   0. ,  19. ],
       [100. ,   0. ,   1. ,   1. ,   0. ,   0. ,  27. ],
       [ 98. ,

In [23]:
transformer.fit_transform(x_test)

array([[ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [ 99.,   1.,   0.,   1.,   0.,   0.,  59.],
       [103.,   0.,   0.,   0.,   1.,   0.,  69.],
       [101.,   0.,   0.,   1.,   0.,   0.,  49.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [102.,   1.,   0.,   1.,   0.,   0.,  33.],
       [102.,   0.,   0.,   1.,   0.,   0.,  49.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [104.,   0.,   0.,   0.,   1.,   0.,  17.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [ 99.,   1.,   0.,   0.,   1.,   0.,  25.],
       [100.,   1.,   0.,   0.,   1.,   0.,  11.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [102.,   1.,   0.,   0.,   0.,   0.,  24.],
       [100.,   1.,   0.,   0.,

In [24]:
transformer.fit_transform(x_test).shape

(20, 7)